export const INIT_STATES="STATES.INIT_STATES";
export const LOADING="STATES.LOADING";
export const ERROR="STATES.ERROR";
export const INIT_STATEVIEW="STATES.INIT_STATEVIEW";
export const INIT_EDITEDSTATE="STATES.INIT_EDITED_STATE";
